name: Mirror to github-mirror.packet.net

on: [ push, delete, create ]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PACKET_IMAGES_MIRROR_SSH_KEY }}
        with:
          source-repo: 'git@github.com:ScottGarman/lfs-testing.git'
          destination-repo: 'git@github-mirror.packet.net:packethost/lfs-testing.git'
